In [5]:
from __future__ import print_function
import torch

In [3]:
torch.cuda.get_device_name(0)

'GeForce RTX 2060 SUPER'

In [13]:
torch.empty(5, 3)

tensor([[5.3598e-08, 2.4830e-18, 1.8788e+31],
        [7.9303e+34, 6.1949e-04, 7.3313e+22],
        [7.2151e+22, 2.8404e+29, 2.3089e-12],
        [7.1856e+22, 4.3605e+27, 2.5226e-18],
        [3.3799e-18, 7.1760e+22, 7.2250e+28]])

In [12]:
torch.rand(5, 3)

tensor([[0.1400, 0.1311, 0.9821],
        [0.5148, 0.2708, 0.7649],
        [0.4077, 0.4126, 0.1800],
        [0.6767, 0.3370, 0.5648],
        [0.0966, 0.7589, 0.3253]])

In [11]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])