In [5]:
torch.cuda.current_device()

In [3]:
torch.cuda.device(0)

'GeForce RTX 2060 SUPER'

In [13]:
torch.cuda.device_count()

tensor([[5.3598e-08, 2.4830e-18, 1.8788e+31],
        [7.9303e+34, 6.1949e-04, 7.3313e+22],
        [7.2151e+22, 2.8404e+29, 2.3089e-12],
        [7.1856e+22, 4.3605e+27, 2.5226e-18],
        [3.3799e-18, 7.1760e+22, 7.2250e+28]])

In [12]:
torch.cuda.get_device_name(0)

tensor([[0.1400, 0.1311, 0.9821],
        [0.5148, 0.2708, 0.7649],
        [0.4077, 0.4126, 0.1800],
        [0.6767, 0.3370, 0.5648],
        [0.0966, 0.7589, 0.3253]])

In [11]:
torch.cuda.is_available()

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
# setting device on GPU if available, else CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

#Additional Info when using cuda
if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024,1), 'MB')
#     print('Cached:   ', round(torch.cuda.memory_cached(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_reserved(0)/1024,1), 'MB')

In [ ]:
torch.rand(10).to(device)

In [ ]:
torch.rand(10, device=device)

In [ ]:
torch.cuda.memory_stats()

In [ ]:
torch.cuda.max_memory_allocated()

In [ ]:
torch.cuda.memory_allocated(0)

In [ ]:
torch.cuda.memory_reserved(0)