In [2]:
from platform import python_version

print(python_version())

3.8.5


In [2]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://pypi.fury.io/zchcRumz4r8ovaFYUPon/cloverhealth/
     |████████████████████████████████| 320.5 MB 11.4 MB/s eta 0:00:01    |█████                           | 50.8 MB 11.2 MB/s eta 0:00:25     |███████                         | 69.9 MB 8.7 MB/s eta 0:00:29     |███████████████████████▊        | 237.7 MB 14.8 MB/s eta 0:00:06
     |████████████████████████████████| 1.3 MB 7.8 MB/s eta 0:00:01
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
     |████████████████████████████████| 42 kB 613 kB/s  eta 0:00:01
     |████████████████████████████████| 6.8 MB 14.2 MB/s eta 0:00:01
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
     |████████████████████████████████| 3.4 MB 12.0 MB/s eta 0:00:01
  Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
     |████████████████████████████████| 65 kB 937 kB/s  eta 0:00:01
     |████████████████████████████████| 127 kB 14.5 MB/s eta 0:00:01
     |████████████████████████████████| 2.9 MB

In [3]:
import tensorflow as tf

/home/hey/.pyenv/versions/3.8.5/envs/self_jupyter_notebooks/lib/python3.8/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [5]:
tf.test.is_built_with_cuda()

True

In [6]:
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  0


In [7]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [8]:
tf.test.is_built_with_cuda()

True

In [9]:
tf.test.is_built_with_gpu_support()

True

In [10]:
print(tf.__version__)

2.3.0


In [11]:
!pip install torch torchvision

     |████████████████████████████████| 748.8 MB 79 kB/s s eta 0:00:01   |▉                               | 20.0 MB 1.6 MB/s eta 0:07:32     |█▎                              | 30.7 MB 9.3 MB/s eta 0:01:17     |█▍                              | 32.6 MB 9.3 MB/s eta 0:01:17     |███▉                            | 89.7 MB 4.8 MB/s eta 0:02:18     |██████                          | 138.7 MB 3.8 MB/s eta 0:02:41     |██████████▌                     | 246.0 MB 4.4 MB/s eta 0:01:55     |██████████████▊                 | 344.3 MB 7.2 MB/s eta 0:00:57     |██████████████▉                 | 347.1 MB 7.2 MB/s eta 0:00:56     |█████████████████▍              | 407.2 MB 15.5 MB/s eta 0:00:23     |██████████████████▋             | 434.3 MB 1.6 MB/s eta 0:03:20     |████████████████████            | 466.7 MB 8.6 MB/s eta 0:00:33     |████████████████████▉           | 486.9 MB 13.0 MB/s eta 0:00:21     |██████████████████████▎         | 520.7 MB 9.1 MB/s eta 0:00:25     |██████████████████████▋        

In [12]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.4881, 0.7684, 0.1477],
        [0.6722, 0.6547, 0.6031],
        [0.0559, 0.7414, 0.6955],
        [0.3350, 0.0434, 0.0156],
        [0.7453, 0.3163, 0.1239]])


In [13]:
import numpy as np

a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [14]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [15]:
np.add(a, 1, out=a)
a

array([2., 2., 2., 2., 2.])

In [16]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [17]:
torch.cuda.current_device()

0

In [18]:
torch.cuda.device(0)

In [19]:
torch.cuda.device_count()

1

In [20]:
torch.cuda.get_device_name(0)

'GeForce RTX 2060 SUPER'

In [21]:
torch.cuda.is_available()

True

In [34]:
# setting device on GPU if available, else CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

#Additional Info when using cuda
if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024,1), 'MB')
#     print('Cached:   ', round(torch.cuda.memory_cached(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_reserved(0)/1024,1), 'MB')

Using device: cuda

GeForce RTX 2060 SUPER
Memory Usage:
Allocated: 1.5 MB
Cached:    2048.0 MB


In [24]:
torch.rand(10).to(device)

tensor([0.0894, 0.9722, 0.1894, 0.7359, 0.0097, 0.2451, 0.1773, 0.8162, 0.2241,
        0.0305], device='cuda:0')

In [27]:
torch.rand(10, device=device)

tensor([0.3061, 0.3002, 0.0928, 0.4943, 0.1036, 0.2409, 0.0161, 0.9883, 0.3594,
        0.0591], device='cuda:0')

In [29]:
torch.cuda.memory_stats()

OrderedDict([('active.all.allocated', 60),
             ('active.all.current', 3),
             ('active.all.freed', 57),
             ('active.all.peak', 9),
             ('active.large_pool.allocated', 0),
             ('active.large_pool.current', 0),
             ('active.large_pool.freed', 0),
             ('active.large_pool.peak', 0),
             ('active.small_pool.allocated', 60),
             ('active.small_pool.current', 3),
             ('active.small_pool.freed', 57),
             ('active.small_pool.peak', 9),
             ('active_bytes.all.allocated', 33792),
             ('active_bytes.all.current', 1536),
             ('active_bytes.all.freed', 32256),
             ('active_bytes.all.peak', 4608),
             ('active_bytes.large_pool.allocated', 0),
             ('active_bytes.large_pool.current', 0),
             ('active_bytes.large_pool.freed', 0),
             ('active_bytes.large_pool.peak', 0),
             ('active_bytes.small_pool.allocated', 33792),
      

In [30]:
torch.cuda.max_memory_allocated()

4608

In [31]:
torch.cuda.memory_allocated(0)

1536

In [32]:
torch.cuda.memory_reserved(0)

2097152