# [What is PyTorch](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [1]:
from __future__ import print_function
import torch

In [2]:
torch.cuda.get_device_name(0)

'GeForce RTX 2060 SUPER'

In [11]:
torch.empty(5, 3)

tensor([[-3.1835e-29,  3.0883e-41, -3.1518e-29],
        [ 3.0883e-41,  8.9683e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -3.2443e-29],
        [ 3.0883e-41,  2.5226e-18,  6.4825e-10],
        [ 1.0527e-11,  7.7202e-10,  2.6227e-09]])

In [10]:
torch.rand(5, 3)

tensor([[0.5806, 0.9308, 0.0799],
        [0.2449, 0.8339, 0.4727],
        [0.5678, 0.6689, 0.4087],
        [0.9653, 0.2124, 0.4335],
        [0.0667, 0.9433, 0.2345]])

In [5]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
torch.tensor([5.5, 3])

tensor([5.5000, 3.0000])

In [8]:
torch.empty(1,1).dtype

torch.float32

In [13]:
x = torch.tensor([5.5, 3])
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6324, -0.0717,  0.4254],
        [ 1.2327, -0.6506, -0.1588],
        [-0.1804,  0.6956,  0.2353],
        [ 0.4947, -0.2844, -0.3999],
        [ 0.2920,  0.3837, -1.6421]])


In [14]:
x.size()

torch.Size([5, 3])

In [20]:
x

tensor([[-0.6324, -0.0717,  0.4254],
        [ 1.2327, -0.6506, -0.1588],
        [-0.1804,  0.6956,  0.2353],
        [ 0.4947, -0.2844, -0.3999],
        [ 0.2920,  0.3837, -1.6421]])

In [21]:
y = torch.ones(5, 3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
x+y

tensor([[ 0.3676,  0.9283,  1.4254],
        [ 2.2327,  0.3494,  0.8412],
        [ 0.8196,  1.6956,  1.2353],
        [ 1.4947,  0.7156,  0.6001],
        [ 1.2920,  1.3837, -0.6421]])

In [24]:
z = torch.ones_like(x)
z

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [30]:
z.add_(x)

tensor([[-1.5295,  0.7132,  2.7017],
        [ 5.9309, -1.6023,  0.3649],
        [ 0.2786,  3.7825,  1.9410],
        [ 2.9788, -0.1375, -0.5995],
        [ 2.1681,  2.5348, -5.5685]])

In [36]:
z[:, 0]

tensor([-1.5295,  5.9309,  0.2786,  2.9788,  2.1681])

In [35]:
z[0]

tensor([-1.5295,  0.7132,  2.7017])

In [52]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
zz = x.view(16, -1)
print(zz)
print(x.size(), y.size(), z.size())

tensor([[-1.4537],
        [ 1.7195],
        [-0.0782],
        [-0.5721],
        [-0.0694],
        [-0.3905],
        [-0.1295],
        [ 1.2811],
        [-0.7277],
        [ 0.9764],
        [ 0.9946],
        [ 1.6546],
        [ 1.4310],
        [ 0.6181],
        [ 0.0306],
        [-0.6189]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [53]:
import numpy as np

In [55]:
np_array = np.ones(5)
np_array

array([1., 1., 1., 1., 1.])

In [56]:
torch.from_numpy(np_array)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [58]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print("GPU not available")

tensor([[-0.4537,  2.7195,  0.9218,  0.4279],
        [ 0.9306,  0.6095,  0.8705,  2.2811],
        [ 0.2723,  1.9764,  1.9946,  2.6546],
        [ 2.4310,  1.6181,  1.0306,  0.3811]], device='cuda:0')
tensor([[-0.4537,  2.7195,  0.9218,  0.4279],
        [ 0.9306,  0.6095,  0.8705,  2.2811],
        [ 0.2723,  1.9764,  1.9946,  2.6546],
        [ 2.4310,  1.6181,  1.0306,  0.3811]], dtype=torch.float64)


In [59]:
device

device(type='cuda')