# [Autograd: Automatic Differentiation](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html)

In [21]:
import torch

In [22]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [23]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [24]:
print(y.grad_fn)

In [25]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [26]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [27]:
out.backward()

In [28]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [29]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [30]:
new_x = torch.ones(4, 4, requires_grad=True)
new_z = ((new_x + torch.rand_like(new_x))*4-1)*new_x
new_o = new_z.mean()
new_o.backward()

new_x.grad

tensor([[0.6638, 0.4569, 0.6374, 0.4903],
        [0.4727, 0.6817, 0.6181, 0.4858],
        [0.5859, 0.6232, 0.6622, 0.4944],
        [0.5842, 0.6271, 0.5258, 0.5235]])

In [31]:
x = torch.randn(3, requires_grad=True)

print(x)

y = x * 2
while y.data.norm() < 1000:
    print(y.data.norm())
    y = y * 2

print(y)

tensor([-0.5287,  0.5019,  0.5141], requires_grad=True)
tensor(1.7841)
tensor(3.5682)
tensor(7.1365)
tensor(14.2729)
tensor(28.5459)
tensor(57.0917)
tensor(114.1834)
tensor(228.3669)
tensor(456.7338)
tensor(913.4676)
tensor([-1082.8430,  1027.9089,  1052.8754], grad_fn=<MulBackward0>)


In [32]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])
